### ISSUE TITLE
Script compilation error on test dataset

### ISSUE THREAD

**Issue by jdiazsupsi** [epi2me-labs/wf-bacterial-genomes#38]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.2.0

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-bacterial-genomes \
    --fastq wf-bacterial-genomes-demo/isolates_fastq \
    --isolates \
    --sample_sheet wf-bacterial-genomes-demo/isolates_sample_sheet.csv \
    -profile standard

### Workflow Execution - CLI Execution Profile

None

### What happened?

Hello, 
I tried running the test dataset before using my own data and I get the following error: 
```
 N E X T F L O W   ~  version 24.04.2

Pulling epi2me-labs/wf-bacterial-genomes ...
 downloaded from https://github.com/epi2me-labs/wf-bacterial-genomes.git
Launching `https://github.com/epi2me-labs/wf-bacterial-genomes` [hopeful_wiles] DSL2 - revision: 6af54574c3 [master]

ERROR ~ Script compilation error
- file : /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/main.nf
- cause: Invalid output definition @ line 862, column 5.
       output(results.all_out)
       ^

1 error
```

I tried other workflows (like wf-metagenomes) and they work, so it does not seem related to the Nextflow installation. I also tried removing the wf with `nextflow drop` and downloading it again but the issue persists. Even trying to get the help message by running `nextflow run epi2me-labs/wf-bacterial-genomes --help` results on the same Script compilation error from above. Do you guys have any idea of what might be causing the issue? Thanks a lot for your time!
Best, 
Juan. 

### Relevant log output

```shell
Jun-26 14:26:54.503 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-bacterial-genomes --fastq wf-bacterial-genomes-demo/isolates_fastq --isolates --sample_sheet wf-bacterial-genomes-demo
/isolates_sample_sheet.csv -profile standard
Jun-26 14:26:54.611 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.2
Jun-26 14:26:54.638 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/bioinfoserver/.nextflow/plugins; core-plugins: nf-amazon@2.5.2,nf-az
ure@1.6.0,nf-cloudcache@0.4.1,nf-codecommit@0.2.0,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2,nf-tower@1.9.1,nf-wave@1.4.2
Jun-26 14:26:54.652 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-26 14:26:54.653 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-26 14:26:54.656 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.10.0 in 'deployment' mode
Jun-26 14:26:54.671 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jun-26 14:26:54.688 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/bioinfoserver/.nextflow/scm
Jun-26 14:26:54.724 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Jun-26 14:26:54.736 [main] INFO  nextflow.cli.CmdRun - Pulling epi2me-labs/wf-bacterial-genomes ...
Jun-26 14:26:54.741 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/epi2me-labs/wf-bacterial-genomes/contents/nextflow.config
Jun-26 14:26:56.419 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/epi2me-labs/wf-bacterial-genomes/contents/main.nf
Jun-26 14:26:56.734 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/epi2me-labs/wf-bacterial-genomes
Jun-26 14:26:56.931 [main] DEBUG nextflow.scm.AssetManager - Pulling epi2me-labs/wf-bacterial-genomes -- Using remote clone url: https://github.com/epi2me-labs/wf-bacterial-genomes.git
Jun-26 14:27:06.109 [main] INFO  nextflow.cli.CmdRun -  downloaded from https://github.com/epi2me-labs/wf-bacterial-genomes.git
Jun-26 14:27:06.143 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/nextflow.config
Jun-26 14:27:06.145 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/nextflow.config
Jun-26 14:27:06.152 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/bioinfoserver/.nextflow/secrets/store.json
Jun-26 14:27:06.156 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@578a5ce8] - activable => nextflow.secret.LocalSecretsProvider@578a5ce8
Jun-26 14:27:06.168 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jun-26 14:27:06.404 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declaration
Jun-26 14:27:06.405 [main] DEBUG nextflow.cli.CmdRun - Launching `https://github.com/epi2me-labs/wf-bacterial-genomes` [hopeful_wiles] DSL2 - revision: 6af54574c3 [master]
Jun-26 14:27:06.407 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jun-26 14:27:06.407 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jun-26 14:27:06.477 [main] DEBUG nextflow.Session - Session UUID: cb1ae23f-847d-4221-90d7-8f22e4fd2928
Jun-26 14:27:06.477 [main] DEBUG nextflow.Session - Run name: hopeful_wiles
Jun-26 14:27:06.478 [main] DEBUG nextflow.Session - Executor pool size: 28
Jun-26 14:27:06.490 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Jun-26 14:27:06.518 [main] DEBUG nextflow.cli.CmdRun -
  Version: 24.04.2 build 5914
  Created: 29-05-2024 06:19 UTC (08:19 CEST)
  System: Linux 4.15.0-213-generic
  Runtime: Groovy 4.0.21 on OpenJDK 64-Bit Server VM 21-internal-adhoc.conda.src
  Encoding: UTF-8 (UTF-8)
  Process: 28691@bioinfoserver [127.0.1.1]
  CPUs: 28 - Mem: 251.4 GB (192.9 GB) - Swap: 976 MB (975 MB) - Virtual threads ON
Jun-26 14:27:06.552 [main] DEBUG nextflow.Session - Work-dir: /home/bioinfoserver/projects/juan/bet/miboc/epi2me/work [ext2/ext3]
Jun-26 14:27:06.588 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jun-26 14:27:06.603 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jun-26 14:27:06.682 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jun-26 14:27:06.691 [main] DEBUG nextflow.util.CustomPoolFactory - Creating virtual thread pool
Jun-26 14:27:06.761 [main] DEBUG nextflow.Session - Session start
Jun-26 14:27:06.765 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow started -- trace file: /home/bioinfoserver/projects/juan/bet/miboc/epi2me/output/execution/trace.txt
Jun-26 14:27:06.770 [main] DEBUG nextflow.Session - Using default localLib path: /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/lib
Jun-26 14:27:06.774 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/lib
Jun-26 14:27:06.774 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/lib/nfcore_external_java_deps.jar
Jun-26 14:27:07.996 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
Jun-26 14:27:08.004 [main] ERROR nextflow.cli.Launcher - Script compilation error
- file : /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/main.nf
- cause: Invalid output definition @ line 862, column 5.
       output(results.all_out)
       ^

1 error

nextflow.exception.ScriptCompilationException: Script compilation error
- file : /home/bioinfoserver/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/main.nf
- cause: Invalid output definition @ line 862, column 5.
       output(results.all_out)
       ^

1 error

        at nextflow.script.ScriptParser.parse0(ScriptParser.groovy:196)
        at nextflow.script.ScriptParser.parse(ScriptParser.groovy:206)
        at nextflow.script.ScriptRunner.parseScript(ScriptRunner.groovy:229)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:136)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:372)
        at nextflow.cli.Launcher.run(Launcher.groovy:503)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script_e5c63c8040c5e648: 862: Invalid output definition @ line 862, column 5.
       output(results.all_out)
       ^

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:980)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:572)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:585)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:639)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:643)
        at nextflow.script.ScriptParser.parse0(ScriptParser.groovy:175)
        ... 6 common frames omitted
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by jdiazsupsi** [comment]
Hi @julibeg, 
I created a new conda environment with Nextflow 23.10.1 and it run to completion. 
Thanks a lot for the quick solution!
