### ISSUE TITLE
Pipeline failure from process 'calling_pipeline:makeReport"

### ISSUE THREAD

**Issue by forty2wallabyway** [epi2me-labs/wf-bacterial-genomes#45]
### Operating System

Ubuntu 22.04

### Workflow Version

1.3.0

### Workflow Execution

Command line (Cluster)

### Other workflow execution

In Conda environment

### Workflow Execution - CLI Execution Profile

None

### What happened?

This is an issue that seems to occur during a handful of different executions; however, today it occurred after attempting to execute the following:

nextflow run main.nf -profile singularity --bam /lab_data/daniels_lab/tysh/nanopore_seq/calls.bam  --out_dir /lab_data/des/ --reference_based_assembly --reference ../references/mycobacteria/NZ_HG964481.1.fasta --override_basecaller_cfg dna_r9.4.1_e8_hac@v3.3

### Relevant log output

```shell
Caused by:
  Process `calling_pipeline:makeReport` terminated with an error exit status (1)


Command executed:

  workflow-glue report     --stats per_read_stats/*          --prokka               --versions versions     --params params.json     --output wf-bacterial-genomes-report.html     --sample_ids calls

Command exit status:
  1

Command output:
  (empty)

Command error:
  [07:13:01 - workflow_glue] Bootstrapping CLI.
  [07:13:12 - matplotlib] Matplotlib created a temporary cache directory at /tmp/matplotlib-18dbyb0q because the default path (/home/tsherman/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  [07:13:13 - matplotlib.font_manager] generated new fontManager
  [07:13:13 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/tsherman/wf-bacterial-genomes/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/tsherman/wf-bacterial-genomes/bin/workflow_glue/__init__.py", line 82, in cli
      args.func(args)
    File "/home/tsherman/wf-bacterial-genomes/bin/workflow_glue/report.py", line 594, in main
      report = create_report(args, logger)
    File "/home/tsherman/wf-bacterial-genomes/bin/workflow_glue/report.py", line 290, in create_report
      zip(args.sample_ids_with_stats, args.stats), key=lambda x: x[0]
  TypeError: 'NoneType' object is not iterable
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by cjalder** [comment]
Hi @forty2wallabyway thanks for raising this issue. It seems like the workflow isn't finding the per-read-stats file for the sample. How many reads are in the bam file? Do you happen to have the full log you can send to us. 
Thanks!

**Comment by forty2wallabyway** [comment]
Thanks for the response @cjalder - there looks to be 698,780 reads in the bam file (checked using samtools). 

I attached the nextflow.log: [nextflow.log.log](https://github.com/user-attachments/files/17035155/nextflow.log.log)

**Comment by xiranli007** [comment]
hello I have the exact same issue, is it solved?

**Comment by forty2wallabyway** [comment]
Hi @xiranli007, I haven't heard back yet, and haven't been able to resolve the issue, though I did find a workaround by adding the following line into the main.nf under the failing process:

errorStrategy 'ignore'

**Comment by cjalder** [comment]
Hi guys - could you update the workflow to v1.4.1 and see if the problem persists?

**Comment by forty2wallabyway** [comment]
Thank you @cjalder - the update resolved the issue for me!

**Comment by amirh-hajianpour** [comment]
Hello everyone! My problem persists even after updating the workflow to the last verion (`v1.4.1-gf73d06f`). Here's my log file: 
[epi2me_bacterial.log](https://github.com/user-attachments/files/17871755/epi2me_bacterial.log)

**Comment by cjalder** [comment]
hi @amirh-hajianpour - looking at your log it seems like the barcodes in the directory and the sample sheet arent matching, meaning no samples are being passed to the workflow.

**Comment by KateK** [comment]
Hi, 

I faced similar problem with the latest version of workflow `v1.4.1-gf73d06f`

`Caused by:
  Process `calling_pipeline:makeReport` terminated with an error exit status (1)


Command executed:

  workflow-glue report     --stats per_read_stats/*          --prokka     --denovo          --versions versions     --params params.json     --output wf-bacterial-genomes-report.html     --sample_ids c6765d00        --wf_version v1.4.1

Command exit status:
  1

Command output:
  (empty)

Command error:
  [15:57:44 - workflow_glue] Bootstrapping CLI.
  [15:58:38 - matplotlib] Matplotlib created a temporary cache directory at /tmp/matplotlib-xed9ag02 because the default path (/opt/custflow/epi2meuser/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Fontconfig error: No writable cache directories
  [15:58:42 - matplotlib.font_manager] generated new fontManager
  [15:58:51 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow_glue/__init__.py", line 82, in cli
      args.func(args)
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow_glue/report.py", line 532, in main
      report = create_report(args, logger)
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow_glue/report.py", line 223, in create_report
      zip(args.sample_ids_with_stats, args.stats), key=lambda x: x[0]
  TypeError: 'NoneType' object is not iterable

Work dir:
  /storage/knowis/temp_work3/a2/48832762b92c288fc845cbca630345

Container:
  ontresearch/wf-common:shad28e55140f75a68f59bbecc74e880aeab16ab158

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (1)

`

**Comment by KateK** [comment]
Hi, 

I faced similar problem with the latest version of workflow `v1.4.1-gf73d06f`

```
Caused by:
  Process `calling_pipeline:makeReport` terminated with an error exit status (1)


Command executed:

  workflow-glue report     --stats per_read_stats/*          --prokka     --denovo          --versions versions     --params params.json     --output wf-bacterial-genomes-report.html     --sample_ids c6765d00        --wf_version v1.4.1

Command exit status:
  1

Command output:
  (empty)

Command error:
  [15:57:44 - workflow_glue] Bootstrapping CLI.
  [15:58:38 - matplotlib] Matplotlib created a temporary cache directory at /tmp/matplotlib-xed9ag02 because the default path (/opt/custflow/epi2meuser/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Fontconfig error: No writable cache directories
  [15:58:42 - matplotlib.font_manager] generated new fontManager
  [15:58:51 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow_glue/__init__.py", line 82, in cli
      args.func(args)
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow_glue/report.py", line 532, in main
      report = create_report(args, logger)
    File "/home/knowis/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/bin/workflow_glue/report.py", line 223, in create_report
      zip(args.sample_ids_with_stats, args.stats), key=lambda x: x[0]
  TypeError: 'NoneType' object is not iterable

Work dir:
  /storage/knowis/temp_work3/a2/48832762b92c288fc845cbca630345

Container:
  ontresearch/wf-common:shad28e55140f75a68f59bbecc74e880aeab16ab158

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (1)

```

**Comment by cjw85** [comment]
@Raviteja-gajula 

Please contact support@nanoporetech.com for help with your issue.

And in future, please do not comment on unrelated (and closed) issues.
