### ISSUE TITLE
Stopped with error - medakaInference_consensus

### ISSUE THREAD

**Issue by hwangumn** [epi2me-labs/wf-bacterial-genomes#51]
### Operating System

Windows 11

### Workflow Version

v.1.4.1

### Workflow Execution

EPI2ME Desktop (Local)

### EPI2ME Version

v5.2.2

### Workflow Execution - CLI Execution Profile

None

### What happened?

Stopped with errors when running calling_pipeline:medakaInference_consensus
Seems like the model was missing. 

### Relevant log output

```shell
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'calling_pipeline:medakaInference_consensus (6)'

Caused by:
  Process `calling_pipeline:medakaInference_consensus (6)` terminated with an error exit status (1)

Command executed:

  medaka --version
      echo dna_r10.4.1_e8.2_400bps_fast@v4.3.0:consensus
      medaka inference align.bam "barcode73.consensus_probs.hdf"         --threads 2 --regions "contig_14:0-247046
  " --model dna_r10.4.1_e8.2_400bps_fast@v4.3.0:consensus

Command exit status:
  1

Command output:
  medaka 2.0.0
  dna_r10.4.1_e8.2_400bps_fast@v4.3.0:consensus

Command error:
  Cannot import pyabpoa, some features may not be available.
  medaka 2.0.0
  dna_r10.4.1_e8.2_400bps_fast@v4.3.0:consensus
  Cannot import pyabpoa, some features may not be available.
  Failed to interpret 'dna_r10.4.1_e8.2_400bps_fast@v4.3.0:consensus' as a basecaller model.
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 35, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/models.py", line 55, in resolve_model
      raise ValueError(
  ValueError: Model dna_r10.4.1_e8.2_400bps_fast@v4.3.0:consensus is not a known model or existant file.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/medaka", line 8, in 
      sys.exit(main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 822, in main
      args = parser.parse_args()
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1768, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1988, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1965, in consume_positionals
      take_action(action, args)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1159, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 2006, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1946, in consume_optional
      take_action(action, args, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 38, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: Model dna_r10.4.1_e8.2_400bps_fast@v4.3.0:consensus is not a known model or existant file..

Work dir:
  /mnt/c/Users/whleo/epi2melabs/instances/wf-bacterial-genomes_01JE9XMXQTQR0SWHP1696RXH51/work/ee/d102ffc876fd82c0a20d6d03575697

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

### Were you able to successfully run the latest version of the workflow with the demo data?

other (please describe below)

**Comment by cjw85** [comment]
Hi @hwangumn,

It is not that the model is missing, it is that your data was basecalled with a "fast" basecaller variant but that medaka supports only the "hac" and "sup" variants.

You should rebasecall your data with the "hac" variant.

**Comment by hwangumn** [comment]
Thanks for the clarification!
Do you also recommend removing the barcodes before feeding the sequences to the bacterial genome wf?
Thanks,
